# 🌳🌳 Random Forest Regressor

## 🔰 Import Libraries

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score

## 🔰 Load CSV

In [2]:
df = pd.read_csv("bankloan.csv")

In [3]:
df

        ID  Age  Experience  Income  ZIP.Code  ...  Personal.Loan  Securities.Account  CD.Account  Online  CreditCard
0        1   25           1      49     91107  ...              0                   1           0       0           0
1        2   45          19      34     90089  ...              0                   1           0       0           0
2        3   39          15      11     94720  ...              0                   0           0       0           0
3        4   35           9     100     94112  ...              0                   0           0       0           0
4        5   35           8      45     91330  ...              0                   0           0       0           1
...    ...  ...         ...     ...       ...  ...            ...                 ...         ...     ...         ...
4995  4996   29           3      40     92697  ...              0                   0           0       1           0
4996  4997   30           4      15     92037  ...              0                   0           0       1           0
4997  4998   63          39      24     93023  ...              0                   0           0       0           0
4998  4999   65          40      49     90034  ...              0                   0           0       1           0
4999  5000   28           4      83     92612  ...              0                   0           0       1           1

[5000 rows x 14 columns]

In [4]:
df.head()

   ID  Age  Experience  Income  ZIP.Code  ...  Personal.Loan  Securities.Account  CD.Account  Online  CreditCard
0   1   25           1      49     91107  ...              0                   1           0       0           0
1   2   45          19      34     90089  ...              0                   1           0       0           0
2   3   39          15      11     94720  ...              0                   0           0       0           0
3   4   35           9     100     94112  ...              0                   0           0       0           0
4   5   35           8      45     91330  ...              0                   0           0       0           1

[5 rows x 14 columns]

## 🔰 Features & Target

In [5]:
x = df.drop("CreditCard", axis=1)

In [6]:
y = df["CreditCard"]

## 🔰 Train-Test Split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

## 🔰 Train Decision Tree Model

In [8]:
model = RandomForestRegressor()

In [9]:
model.fit(x_train, y_train)

RandomForestRegressor()

## 🔰 Prediction

In [12]:
y_pred = model.predict(x_test)

In [13]:
y_pred

array([0.41, 0.25, 0.16, 0.  , 0.31, 0.16, 0.17, 0.35, 0.4 , 0.46, 0.33,
       0.98, 0.41, 0.35, 0.29, 0.46, 0.43, 0.32, 0.22, 0.41, 0.44, 0.26,
       0.25, 0.23, 0.11, 0.21, 0.17, 0.18, 0.19, 0.02, 0.33, 0.28, 0.17,
       0.49, 0.17, 0.38, 0.22, 0.27, 0.53, 0.36, 0.93, 0.46, 0.84, 0.49,
       0.3 , 0.08, 0.32, 0.8 , 0.37, 0.25, 0.36, 0.58, 0.3 , 0.56, 0.27,
       0.87, 0.16, 0.27, 0.15, 0.19, 0.4 , 0.45, 0.24, 0.2 , 0.18, 0.29,
       0.39, 0.01, 0.43, 0.42, 0.31, 0.19, 0.95, 0.49, 0.18, 0.35, 0.23,
       0.36, 0.51, 0.39, 0.23, 0.33, 0.25, 0.13, 0.51, 0.45, 0.4 , 0.3 ,
       0.44, 0.3 , 0.28, 0.35, 0.29, 0.31, 0.23, 0.54, 0.33, 0.03, 0.32,
       0.24, 0.24, 0.25, 0.15, 0.52, 0.49, 0.39, 0.22, 0.47, 0.11, 0.43,
       0.13, 0.2 , 0.46, 0.1 , 0.38, 0.33, 0.39, 0.25, 0.3 , 0.34, 0.33,
       0.28, 0.48, 0.84, 0.37, 0.47, 0.45, 0.49, 0.39, 0.37, 0.26, 0.24,
       0.2 , 0.09, 0.25, 0.43, 0.2 , 0.27, 0.  , 0.38, 0.83, 0.04, 0.26,
       0.27, 0.43, 0.47, 0.31, 0.24, 0.49, 0.12, 0.16, 0.36, 0.27, 0.29,
       0.02, 0.24, 0.23, 0.14, 0.11, 0.53, 0.3 , 0.29, 0.19, 0.13, 0.23,
       0.32, 0.14, 0.12, 0.33, 0.22, 1.  , 0.3 , 0.51, 0.26, 0.42, 0.2 ,
       0.19, 0.21, 0.15, 0.48, 0.41, 0.19, 0.05, 0.24, 0.49, 0.37, 0.15,
       0.61, 0.28, 0.62, 0.  , 0.  , 0.19, 0.23, 0.6 , 0.28, 0.29, 0.01,
       0.23, 0.26, 0.38, 0.29, 0.25, 0.74, 0.16, 0.15, 0.28, 0.39, 0.8 ,
       0.15, 0.47, 0.3 , 0.41, 0.45, 0.14, 0.32, 0.25, 0.29, 0.36, 0.36,
       0.45, 0.28, 0.25, 0.29, 0.24, 0.54, 0.17, 0.8 , 0.33, 0.11, 0.1 ,
       0.19, 0.28, 0.29, 0.35, 0.11, 0.13, 0.22, 0.35, 0.38, 0.4 , 0.4 ,
       0.47, 0.  , 0.33, 0.23, 1.  , 0.08, 0.19, 0.33, 0.21, 0.35, 0.01,
       0.  , 0.29, 0.24, 0.21, 0.29, 0.21, 0.25, 0.12, 0.05, 0.95, 0.26,
       0.3 , 0.62, 0.09, 0.02, 0.43, 0.32, 0.43, 0.27, 0.  , 0.21, 0.16,
       0.26, 0.27, 0.26, 0.22, 0.43, 0.24, 0.35, 0.16, 0.94, 0.97, 0.34,
       0.28, 0.03, 0.12, 0.37, 0.  , 0.43, 0.3 , 0.38, 0.36, 0.1 , 0.  ,
       0.27, 0.99, 0.3 , 0.49, 0.35, 0.32, 1.  , 0.44, 0.39, 0.2 , 0.22,
       0.18, 0.22, 0.  , 0.64, 0.17, 0.76, 0.13, 0.34, 0.25, 0.31, 0.38,
       0.18, 0.41, 0.33, 0.34, 0.23, 0.29, 0.29, 0.3 , 0.04, 0.15, 0.25,
       0.33, 0.22, 0.33, 0.22, 0.29, 0.34, 0.38, 0.98, 0.35, 0.48, 0.42,
       0.46, 0.25, 0.39, 0.  , 0.33, 0.37, 0.99, 0.28, 0.25, 0.35, 0.  ,
       0.14, 0.29, 0.16, 0.36, 0.33, 0.  , 0.32, 0.45, 0.82, 0.08, 0.51,
       0.16, 0.16, 0.39, 0.34, 0.17, 0.37, 0.28, 0.11, 0.38, 0.27, 0.27,
       0.22, 0.24, 0.21, 0.04, 0.31, 0.51, 0.3 , 0.78, 0.57, 0.3 , 0.36,
       0.22, 0.56, 0.26, 0.33, 0.42, 0.  , 0.39, 0.25, 0.43, 0.32, 0.48,
       0.05, 0.23, 0.41, 0.25, 0.15, 0.25, 0.45, 0.27, 0.32, 0.27, 0.22,
       0.39, 0.41, 0.16, 0.22, 0.32, 0.07, 0.3 , 0.38, 0.44, 0.29, 0.48,
       0.56, 0.07, 0.22, 0.18, 0.14, 0.25, 0.17, 0.66, 0.2 , 0.53, 0.49,
       0.25, 0.39, 0.52, 0.38, 0.29, 1.  , 0.33, 0.22, 0.32, 0.38, 0.42,
       0.33, 0.35, 0.08, 0.38, 0.26, 0.35, 0.04, 0.47, 0.36, 0.  , 0.18,
       0.99, 0.34, 0.35, 0.38, 0.82, 0.  , 0.31, 0.07, 0.13, 0.28, 0.32,
       0.43, 0.17, 0.35, 0.23, 0.44, 0.28, 0.44, 0.46, 0.38, 0.25, 0.46,
       0.12, 0.24, 0.08, 0.33, 0.31, 0.39, 0.45, 0.25, 0.27, 0.41, 0.97,
       0.26, 0.13, 0.24, 0.46, 0.49, 0.45, 0.35, 0.33, 0.31, 0.55, 0.08,
       0.31, 0.27, 0.36, 0.31, 0.39, 0.19, 0.34, 0.32, 0.04, 0.27, 0.45,
       0.25, 0.51, 0.22, 0.32, 0.26, 0.24, 0.3 , 0.3 , 0.1 , 0.09, 0.  ,
       0.22, 0.32, 0.2 , 0.23, 0.36, 0.33, 0.17, 0.29, 0.58, 0.24, 0.29,
       0.15, 0.51, 0.24, 0.21, 0.45, 0.44, 0.18, 0.43, 0.28, 0.1 , 0.42,
       0.23, 0.33, 0.19, 0.16, 0.34, 0.35, 0.58, 0.08, 0.  , 0.39, 0.4 ,
       0.16, 0.28, 0.89, 0.18, 0.49, 0.24, 0.42, 0.48, 0.31, 0.28, 0.4 ,
       0.  , 0.32, 0.37, 0.39, 0.45, 0.32, 0.51, 0.27, 0.09, 0.27, 0.39,
       0.38, 0.24, 0.53, 0.52, 0.32, 0.29, 0.38, 0.16, 0.21, 0.29, 0.38,
       0.42, 0.23, 0.31, 0.34, 0.27, 0.25, 0.26, 0.19, 0.53, 0.06, 0.19,
       0.35, 0.25, 0.  , 0.21, 0.33, 0.21, 0.45, 0.18, 0.35, 0.29, 0.45,
       0.27, 0.31, 0.23, 0.21, 0.46, 0.41, 0.29, 0.33, 0.34, 0.3 , 0.34,
       0.27, 0.18, 0.27, 0.  , 0.21, 0.32, 0.02, 0.56, 0.39, 0.93, 0.21,
       0.39, 0.3 , 0.32, 0.24, 0.44, 0.38, 0.23, 0.18, 0.31, 0.19, 0.38,
       0.22, 0.31, 0.98, 0.19, 0.32, 0.34, 0.25, 0.23, 0.38, 0.2 , 0.21,
       0.61, 0.29, 0.22, 0.23, 0.35, 0.33, 0.34, 0.47, 0.86, 0.  , 0.05,
       0.3 , 0.55, 0.28, 0.25, 0.22, 0.3 , 0.31, 0.33, 0.21, 0.24, 0.33,
       0.  , 0.2 , 0.31, 0.  , 0.44, 0.49, 0.45, 0.26, 0.16, 0.29, 0.26,
       0.31, 0.34, 0.08, 0.16, 0.42, 0.3 , 0.04, 0.36, 0.14, 0.3 , 0.34,
       0.3 , 0.34, 0.16, 0.  , 0.28, 0.12, 0.3 , 0.57, 0.33, 0.32, 0.2 ,
       0.14, 0.33, 0.24, 0.01, 0.39, 0.33, 0.32, 0.4 , 0.18, 0.12, 0.34,
       0.45, 0.27, 0.22, 0.14, 0.44, 0.12, 0.22, 0.33, 0.28, 0.4 , 0.46,
       0.  , 0.36, 0.47, 0.  , 0.54, 0.22, 0.27, 0.38, 0.31, 0.39, 0.39,
       0.33, 0.15, 0.08, 0.01, 0.34, 0.32, 0.37, 0.  , 0.27, 0.34, 0.03,
       0.34, 0.22, 0.43, 0.96, 0.45, 0.3 , 0.44, 0.35, 0.28, 0.03, 0.3 ,
       0.38, 0.34, 0.47, 0.23, 0.28, 0.1 , 0.26, 0.58, 0.42, 0.36, 0.41,
       0.41, 0.23, 0.01, 0.27, 0.2 , 0.29, 0.22, 0.29, 0.47, 0.16, 0.34,
       0.22, 1.  , 0.42, 0.46, 0.33, 0.18, 0.97, 0.21, 0.  , 0.42, 0.17,
       0.38, 0.  , 0.97, 0.28, 0.36, 0.36, 0.93, 0.33, 0.34, 0.01, 0.28,
       0.26, 0.29, 1.  , 0.24, 0.22, 0.  , 0.47, 0.32, 0.36, 0.16, 0.84,
       0.29, 0.32, 0.3 , 0.24, 0.34, 0.99, 0.2 , 0.93, 0.25, 0.26, 0.47,
       0.26, 0.36, 0.23, 0.14, 0.29, 0.26, 0.12, 0.04, 0.39, 0.15, 0.05,
       0.44, 0.36, 0.25, 0.29, 0.25, 0.97, 0.01, 0.22, 0.27, 0.38, 0.31,
       0.23, 0.05, 0.34, 0.39, 0.27, 0.86, 0.23, 0.44, 0.39, 0.4 , 0.64,
       0.11, 0.28, 0.2 , 0.25, 0.35, 0.31, 0.01, 0.53, 0.16, 0.31, 0.23,
       0.  , 0.11, 0.17, 0.28, 0.96, 0.48, 0.44, 0.32, 0.24, 0.94, 0.25,
       0.1 , 0.21, 0.25, 0.48, 0.38, 0.31, 0.05, 0.33, 0.72, 0.22, 0.28,
       0.27, 0.15, 0.49, 0.49, 0.56, 0.16, 0.34, 0.35, 0.2 , 0.21, 0.33,
       0.25, 0.79, 0.2 , 0.27, 0.34, 0.28, 0.54, 0.23, 0.37, 0.36, 0.41,
       0.4 , 0.12, 0.19, 0.34, 0.26, 0.24, 0.22, 0.24, 0.22, 0.38, 0.21,
       0.34, 0.  , 0.26, 0.41, 0.33, 0.25, 0.17, 0.48, 0.67, 0.26, 0.42,
       0.45, 0.28, 0.19, 0.51, 0.38, 0.99, 0.21, 0.26, 0.28, 0.17, 0.3 ,
       0.21, 0.28, 0.  , 0.33, 0.23, 0.43, 0.28, 0.35, 0.22, 0.25, 0.99,
       0.29, 0.4 , 0.29, 0.29, 0.  , 0.31, 0.33, 0.25, 0.46, 0.94, 0.85,
       0.25, 0.27, 0.27, 0.39, 0.36, 0.38, 0.5 , 0.04, 0.22, 0.35, 0.36,
       0.03, 0.32, 0.37, 0.53, 0.22, 0.42, 0.2 , 0.18, 0.25, 0.42, 0.32,
       0.25, 0.34, 0.18, 0.43, 0.23, 0.34, 0.25, 0.24, 0.38, 0.31])

## 🔰 Accuracy

In [18]:
ac = accuracy_score(y_pred, y_test)

ValueError: Classification metrics can't handle a mix of continuous and binary targets