# 📉 MULTIPLE LINEAR REGRESSION

## 🧩 Import Library

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

## 🧩 Load the CSV File

In [2]:
df = pd.read_csv("mobile_project.csv")

In [3]:
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [4]:
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

## 🧩 x & y

In [5]:
y = df["price_range"]

In [6]:
x = df.drop(["price_range"], axis=1)

## 🧩 Apply Train–Test Split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [8]:
x_train

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
968,1923,0,0.5,1,7,0,46,0.5,191,1,10,767,1759,1489,10,9,3,1,1,1
240,633,1,2.2,0,0,1,49,0.1,139,8,1,529,1009,3560,11,1,16,1,1,1
819,1236,0,0.9,1,2,1,57,0.1,188,1,14,517,809,1406,14,12,20,1,0,1
692,781,0,1.1,0,2,0,38,0.4,198,5,7,304,1674,3508,13,8,5,0,0,1
420,1456,1,0.5,1,7,0,7,0.4,105,5,12,823,1104,1587,6,5,20,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,1975,1,1.9,1,2,0,31,0.9,151,1,17,775,1607,3022,13,5,19,0,0,1
1294,589,1,0.5,0,1,1,59,0.7,146,8,4,759,1858,362,16,10,6,1,1,1
860,1829,1,0.5,0,0,1,15,0.4,160,5,7,729,1267,2080,16,11,12,1,0,1
1459,1927,0,0.9,1,3,0,11,0.4,190,8,12,491,1506,2916,16,11,18,0,1,1
1126,635,1,0.6,1,1,1,50,0.3,97,5,13,193,989,2107,13,12,12,1,0,0

In [9]:
y_train

968     1
240     2
819     0
692     3
420     1
       ..
1130    3
1294    0
860     2
1459    3
1126    1
Name: price_range, Length: 1600, dtype: int64

## 🧩 Model

In [10]:
model = LinearRegression()

In [11]:
model.fit(x_train,y_train)

LinearRegression()

## 🧩 Prediction & Evaluation

In [12]:
y_pred = model.predict(x_test)

In [13]:
y_pred

array([ 2.55800675e-01,  1.74348404e+00,  8.90845293e-01,  2.98762326e+00,
        1.31379876e+00,  1.35430921e+00,  1.68973722e+00,  2.17768535e-01,
        2.50212545e+00,  1.37283866e+00,  2.52930709e-01,  6.40609743e-01,
        1.80097970e+00,  3.21997166e+00,  2.32436910e+00,  2.09494545e+00,
        3.00663957e+00,  3.46643580e+00,  1.17621418e+00,  1.74000827e-01,
        1.19029695e-01,  1.50097735e+00,  6.84166176e-01,  1.86602711e+00,
        1.86614954e-01,  9.60300103e-01,  2.66338410e+00,  2.25221927e+00,
        1.99312891e+00, -1.40631634e-01,  4.75145459e-01, -3.27717910e-01,
        3.10063461e+00,  2.85011797e-01,  1.33494860e+00,  1.31906244e+00,
        2.22191879e+00,  2.75398128e-01,  3.12061029e+00,  2.94840893e-01,
        1.57026805e+00,  2.51836782e+00,  2.02796754e+00, -8.47332025e-02,
        2.38669136e+00,  2.28163547e+00,  1.66864182e+00,  9.23228975e-01,
        2.91124840e+00,  1.02068677e+00,  3.35002127e+00,  1.12627120e+00,
        9.96739197e-03,  2.17603877e-01,  7.72204123e-01,  6.71349327e-01,
        1.19213429e+00,  2.48544206e+00, -2.46572624e-01, -3.04948404e-01,
        6.12554490e-01,  3.24706368e+00,  2.59917823e+00,  1.06607198e+00,
        4.48782995e-01,  4.50281995e-01,  3.35734061e+00,  3.02233189e+00,
        1.15996033e+00,  1.71509172e+00,  1.68778992e+00,  2.15034457e+00,
       -1.48022556e-01,  9.02663120e-01,  2.21565363e+00,  3.03843150e-01,
        6.32109711e-01,  3.13191630e+00,  2.11758935e+00,  1.63646528e+00,
        2.97419383e+00,  1.63223326e+00,  1.01562166e+00, -2.83307096e-03,
        1.16376936e+00,  2.92862902e+00,  1.38118988e+00,  2.97780902e+00,
        3.11216980e+00,  1.54503359e-01,  2.55033480e+00,  3.44462115e+00,
        1.74745882e+00,  8.60917482e-01,  2.88019537e+00,  1.96395360e+00,
        2.01643030e+00,  3.37840876e+00,  1.36410455e+00,  1.17916330e+00,
       -1.09415101e-01, -3.39797730e-02,  1.00207920e+00,  4.63985694e-01,
        5.72965627e-01,  2.81233063e+00,  2.08828398e+00, -5.49791356e-01,
        8.42108892e-01,  1.10377796e+00, -4.15311472e-01,  2.71558904e-01,
        2.57036606e+00,  1.33452796e+00,  2.37930181e+00,  1.83037874e+00,
        2.48865395e+00,  2.34328713e+00,  2.69479808e-01,  2.05288616e+00,
        8.64734251e-01,  2.87010527e+00,  1.97809525e+00,  1.33912033e+00,
        3.04486001e+00,  2.73272986e+00,  1.56739183e-01,  2.43259069e+00,
        8.16067573e-02,  1.94834583e+00,  2.64973710e+00,  2.94748275e-01,
        1.99616953e+00,  2.10587654e+00, -1.44076626e-02,  2.52060032e+00,
        9.98799891e-01,  2.82826784e-01,  5.71068681e-01,  1.80996859e+00,
        2.42746841e+00,  7.10683333e-01,  2.27970019e+00,  2.14272987e+00,
       -3.24744912e-01,  5.47202713e-02,  3.25174864e-01,  1.20234565e+00,
        1.40814854e+00,  2.10967421e+00,  2.86884364e+00,  1.03160615e+00,
        1.25163831e+00, -2.92824400e-01,  2.17617813e+00,  1.93741890e+00,
        1.08233139e-01,  1.37261331e+00,  3.69805048e-01,  1.51802206e+00,
        1.98233067e+00,  2.48376103e+00,  2.43977444e+00,  2.28021138e+00,
        1.25906931e+00,  1.38314330e-01,  6.41118920e-01,  1.84080468e+00,
        1.89243929e+00,  2.51951710e+00,  2.47549270e+00,  5.99084614e-01,
        6.53484224e-01,  1.31341350e-01,  3.76224811e+00,  9.70991888e-01,
        1.41764536e+00,  1.91816179e+00,  7.02238492e-01,  3.25518484e-01,
       -1.33218004e-02,  1.98493010e-01,  5.13818546e-02,  3.13867781e-01,
        2.96511189e+00,  1.87913936e+00,  8.23427281e-02,  2.51946271e+00,
       -1.65807272e-01,  5.95755397e-02, -1.84081760e-02,  1.43315443e-01,
        9.80108220e-01,  3.04871268e+00,  2.47693726e+00,  1.34233877e+00,
        2.77032071e-01,  1.00661831e+00,  1.42235135e+00,  7.85756257e-01,
        1.02007998e+00,  1.61931569e+00,  1.81101116e+00,  2.38103315e+00,
        2.60938040e+00,  3.11083426e+00,  9.93489650e-01,  2.07510121e+00,
        1.88960453e-01,  4.95332216e-01,  4.57708216e-01,  1.80791143e+00,
        1.18884331e+00,  1.24813846e+00,  2.68051773e+00,  1.25385624e+00,
        5.43334910e-01,  2.24711302e+00,  1.40041246e+00,  1.03560314e+00,
        2.93761974e+00,  1.66510925e+00,  2.57965164e+00,  1.78095318e-01,
        1.45543771e-01,  1.69051120e+00,  7.55516961e-01,  2.48837039e+00,
        1.40023217e-01,  6.60296381e-01,  1.60082905e+00, -3.70657949e-01,
        1.51772411e+00,  3.01845430e+00,  1.67417162e+00,  4.82090464e-01,
        7.58261771e-01,  2.64634142e+00,  2.87133999e+00,  5.42752987e-01,
        1.47954851e+00,  3.08993422e+00,  2.45982395e+00,  3.46304618e+00,
       -6.11238954e-02,  2.82281230e+00,  1.25994026e+00,  2.09724428e+00,
        3.44528281e+00,  2.47233502e+00,  2.21258025e+00,  1.04925272e+00,
        7.47798289e-01,  3.71220175e+00,  2.73884767e+00,  9.52105328e-01,
        2.85064368e+00,  2.77338621e+00,  3.17504682e+00,  2.37830151e+00,
        2.95270853e+00,  1.99730351e-01,  1.51083777e+00,  1.78801210e+00,
        2.32984692e+00,  1.58370069e+00,  2.33960790e+00,  1.26065635e-01,
        1.64841382e+00,  3.01791095e+00,  2.07571833e+00,  2.23479286e+00,
        2.03938133e+00,  7.13613391e-01, -1.52187088e-01,  1.57271498e+00,
        1.75882682e-01,  2.32913613e+00,  3.32762612e+00,  1.20856293e+00,
        3.33098774e+00,  1.03183564e+00,  5.65161319e-01,  3.29952403e+00,
        1.13266016e+00,  1.85718664e+00, -7.78413056e-02, -2.05931979e-01,
        2.56921548e+00,  2.03508495e-02,  1.29560954e+00,  1.88926072e+00,
        3.12699409e+00,  2.80572729e+00,  2.69797497e+00,  5.89783836e-01,
        7.38570875e-01, -1.57745784e-01,  7.74519860e-01,  3.34888835e+00,
        3.40894933e+00,  2.79030424e-01,  9.69863555e-01,  1.49710728e+00,
        1.82770272e+00, -2.22731886e-02,  2.57813376e+00,  3.14156013e+00,
        1.93768832e+00,  3.36622634e+00,  1.55084073e+00,  3.67968128e+00,
        1.96941644e+00, -1.64444304e-01,  1.97433412e+00,  1.24276091e+00,
        1.49655130e+00,  1.34436751e+00, -4.90766877e-01,  8.41479478e-02,
        3.30954724e-01,  2.41316055e+00,  2.33926148e+00,  3.33023744e+00,
        1.07772974e+00,  1.75090293e-01,  1.39600302e+00,  5.13051995e-01,
        1.60620224e+00,  2.46056385e+00,  2.59749898e+00,  4.36695438e-01,
        2.42104619e+00,  2.64473121e+00,  1.90787425e+00,  1.21627581e+00,
        2.46627471e+00,  6.85194892e-02, -8.53020702e-02,  2.36637890e+00,
        9.64109237e-01,  3.41626211e+00,  1.97908024e+00,  2.59258532e-01,
        1.22139535e+00,  1.19665036e+00,  1.46984196e+00,  7.10127436e-01,
        1.28841484e+00,  3.05934396e+00,  1.50043869e+00,  8.63238861e-02,
        4.16679336e-01,  2.45454845e+00,  2.74377532e+00, -5.92457927e-02,
        2.53405183e+00, -6.82795427e-01, -6.85674993e-01,  1.73327605e+00,
       -1.19610353e-01,  7.49819395e-01,  1.74873230e+00,  1.89488201e+00,
        1.87377694e+00,  3.46596628e+00,  3.65016621e-01,  2.45553013e+00,
        1.77221138e+00,  2.34389518e+00,  2.74819846e+00,  2.94767577e+00,
        3.38734929e+00,  1.85803336e+00,  1.29337104e+00,  1.47719319e+00,
        2.34617848e-01,  3.47456289e+00,  1.40122008e+00,  2.68398194e+00,
        2.95803619e+00, -2.34545697e-02,  1.71350083e+00,  3.20494769e+00,
        1.63501874e+00,  3.01666675e+00,  3.45941835e+00,  3.63964258e+00,
        5.52113362e-01, -3.74287535e-01,  1.87137741e+00,  2.93308842e+00,
        4.08981516e-01, -3.28456070e-01,  2.23100329e+00,  3.03016950e+00,
        1.51769189e+00,  1.27710694e+00,  1.22431156e+00,  1.95099820e+00])

## 🧩 r2_score Apply

In [14]:
r2 = r2_score(y_pred, y_test)

In [15]:
r2

0.9127921520465196