# 🧠 SVM (Support Vector Machine) Regressor

## 🔰 Import Libraries

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score

## 🔰 Load CSV

In [10]:
df = pd.read_csv("UniversalBank.csv")

In [11]:
df

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,29,3,40,92697,1,1.9,3,0,0,0,0,1,0
4996,4997,30,4,15,92037,4,0.4,1,85,0,0,0,1,0
4997,4998,63,39,24,93023,2,0.3,3,0,0,0,0,0,0
4998,4999,65,40,49,90034,3,0.5,2,0,0,0,0,1,0
4999,5000,28,4,83,92612,3,0.8,1,0,0,0,0,1,1

In [12]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

## 🔰 Features & Target

In [13]:
x = df.drop("Income", axis=1)

In [14]:
y = df["Income"]

## 🔰 Train-Test Split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [16]:
scaled = StandardScaler()
x_train = scaled.fit_transform(x_train)
x_test = scaled.transform(x_test)

In [17]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

## 🔰 Train Decision Tree Model

In [18]:
model = SVR(kernel = 'rbf')

In [19]:
model.fit(x_train, y_train)

SVR()

## 🔰 Prediction

In [20]:
y_pred = model.predict(x_test)

In [21]:
y_pred

array([ 59.92833215, 127.64767729, 111.6591127 ,  74.71566783,
        39.99040286,  73.13993955, 128.42705692, 140.79022476,
        44.67792535, 123.10487789,  37.69157287,  81.15787185,
       127.84797666,  58.70390027, 103.19467188,  42.18343273,
        60.76575338,  68.65951935,  56.16759122, 127.18045754,
        37.51112087,  90.14047288,  72.03063725,  51.56940868,
        65.06691471,  55.59087696,  55.79568163,  77.31913415,
        84.44760915,  96.16666049, 129.18940391,  78.94789744,
       118.37185647,  88.20466293,  54.92482745,  56.47689796,
        36.38057339,  60.24716207,  64.12551223,  46.47408574,
        67.81631402,  65.06206585, 115.09404376,  98.98707285,
        53.64300122,  69.25159083,  67.24019496,  90.00527102,
       128.22349219,  48.31244481,  46.11971513, 113.55324   ,
       115.26726049,  54.42680572,  70.5291509 ,  73.91546001,
        73.58525573,  51.2205803 ,  33.38894081, 110.85302632,
       136.69050657,  52.74002321,  57.67707337,  66.32640752,
        67.15622773,  36.50331576,  54.09153547, 125.72277722,
        46.36768341,  52.12066243,  47.138065  ,  47.28915971,
       109.77599862,  63.90497587,  61.571297  ,  56.9642785 ,
        65.60617863,  49.847798  ,  45.86790305,  61.06186431,
       128.08787162,  70.94594086, 109.80080337,  62.46336214,
        70.16988054,  43.57095048,  52.11870704,  41.04045925,
        50.82526055,  63.29432008, 136.62739271,  43.01744431,
        69.44373076,  35.03152633,  66.63441477,  86.61544061,
        50.33169247, 134.62368474,  56.18560711,  48.83337107,
        41.35836926,  46.23532474,  48.11023488, 114.22998353,
        66.29833005,  76.41845267,  52.60417748,  68.76547238,
        47.7154026 ,  44.96161853,  43.02758989,  56.84085444,
        50.27863026,  86.80536662,  82.94729936,  61.31061876,
        46.8262711 ,  74.85827366,  69.78970949,  68.41048107,
        45.59950523,  54.77779633,  69.43170314, 117.38998238,
        52.43992959,  58.07001757,  46.51463819,  52.14685553,
        54.41019461, 127.57892412, 135.03778116,  58.09287953,
        35.275298  , 114.35206552,  52.65889172,  65.1361703 ,
        66.24528322,  76.11601446,  71.98256511,  58.48490748,
        73.41817103, 129.82641624,  69.98684379,  67.28525749,
        88.12481252,  38.70519725,  53.81755068,  54.30872065,
        69.93476042,  37.71243619,  74.58253787,  58.73280626,
        46.28008629,  84.23152736, 130.89990322,  49.70505336,
        38.8127965 ,  55.31174557,  49.68481251,  48.57017471,
        42.54812891,  38.69431978,  93.16013361, 111.55827863,
       118.7280198 ,  65.33927054,  56.28009098,  71.00745786,
        69.17286124,  54.41327464,  75.11827414,  38.62776049,
        56.17563237, 122.34906556,  53.60546579,  59.66145958,
        43.0617787 ,  61.74126273,  99.91150036, 114.42344705,
        87.69157931,  45.22546026,  86.69101864,  63.1597141 ,
        48.98831596,  43.45622918,  47.81242402, 106.53649368,
        48.16931377,  53.39499108, 130.22078338,  46.94712087,
        47.82316119,  69.24301554,  74.2951257 ,  43.24358602,
        82.21568445, 136.06200935,  53.1265067 ,  50.71808194,
        41.80757871,  80.46088267,  56.58708137, 109.44582021,
       131.80704008, 112.3133456 ,  28.98963717,  59.03378787,
        79.99451662,  62.4358186 , 122.1746713 ,  59.60172506,
        53.22144326,  65.9413439 ,  38.50278016,  57.08675485,
        67.933753  ,  50.29066207,  41.44494588,  58.27638327,
        56.41277788,  63.28106509,  48.31708412,  46.48990046,
        29.8083151 ,  84.11896812, 101.66568902, 106.78175329,
        46.09957916,  54.35038377,  68.66569497,  52.4052067 ,
        62.58655605,  56.48790457,  72.62525147, 125.63778236,
        66.3756873 ,  67.72153736,  64.7176966 ,  56.57871021,
        34.26178157,  55.81988071,  91.10114461,  65.94159372,
       121.02219199,  33.35612011, 116.08088795,  70.98800248,
        83.20244018,  56.04526178,  87.23714658,  61.45570501,
       134.44977232,  70.5776099 ,  98.43578225,  37.16355703,
        49.34621456,  54.743486  ,  66.67191372,  50.31797666,
       103.64841061,  52.8535586 , 114.49619981,  80.5763269 ,
        62.57023676,  84.12197338,  59.08456565, 130.57557683,
        51.55439607,  55.05504659,  46.48974827,  57.37095992,
        61.18411789,  77.19189887, 103.13432805,  89.4076249 ,
        49.82709526,  94.1269784 ,  59.97644815,  83.76252897,
        49.74069058,  64.3269085 ,  96.00581404,  86.90164318,
        74.60283198,  52.07889318, 100.00169938, 130.93992765,
        43.58278214,  45.53447824,  56.504351  ,  59.82334145,
        72.71961511,  34.50696953,  95.91747731,  45.13957163,
        57.75806799,  44.39287018,  73.9799283 ,  42.08472427,
        59.21397988,  49.1912737 ,  41.21855113, 117.59778428,
        67.8883954 ,  61.60485264,  44.52808379,  28.36688286,
        44.18942266,  50.19929322,  66.82458892,  69.81911166,
        61.26991651,  81.49637395,  57.45744419,  62.3709541 ,
        63.50762234,  28.90889815,  79.95806695,  64.68625017,
        67.12903172,  43.71209988,  56.58419247,  27.20225662,
        49.05940762,  51.87997134,  62.65011844, 122.1995756 ,
        39.82600066,  82.64688573,  85.43516122,  52.81155713,
        57.55893597,  46.87629522,  48.20839105,  52.23548889,
       129.44309514,  77.24887529,  81.5771869 ,  40.95340844,
        73.41946042,  48.74770834,  91.27951974,  51.50988016,
        52.56162987,  50.70128449,  60.7512281 , 118.19027606,
        74.32783915,  45.71236955,  40.41788953,  64.63019402,
        52.84196767, 112.88477004, 111.71008096,  68.70808854,
        79.65410686,  59.97150726,  62.80205205, 114.33188141,
       100.56220499, 126.0596401 ,  37.09039653,  37.74484273,
        82.78689236,  62.36734339,  46.40387515,  37.61128692,
        86.60763329,  41.5035687 , 121.71814898,  67.33708593,
       126.11817297,  39.84512419,  65.54960102,  47.24390396,
        49.40720818, 119.16039708,  45.07984175,  78.64387457,
        45.88110293, 113.32725623,  40.25884343, 115.63533629,
        32.00973668,  75.0918345 ,  55.83470032,  54.30815125,
        57.41270666,  51.74279311,  48.76944951, 128.6355448 ,
        33.86759885,  51.83792076, 127.64197304, 128.30124115,
       122.04674966,  55.91409808,  56.94072482,  28.81726639,
        75.92694065,  55.32152211, 126.80690248,  46.31213021,
        87.57467186,  58.7448945 ,  54.48207175,  57.54040515,
        56.66679772,  76.06900855,  61.02653015,  53.40266837,
       105.5099414 ,  56.39400798,  87.8157677 ,  40.54391452,
        86.51693357,  61.05082578,  48.95814199, 105.50593283,
        31.53715889,  75.93664624,  76.9646827 ,  62.63278981,
        45.34971188,  48.44146521,  81.83060832,  53.50357031,
        54.86487208,  53.11560465,  46.52443722,  83.31279579,
        43.21979001,  55.5457139 ,  79.43846157,  54.03726756,
        61.72792616,  49.43572305,  70.20141132,  37.29972365,
        52.79045626,  62.42534098, 104.22924187,  47.11039399,
        59.75924897,  64.68693636, 127.13053221,  69.97754615,
        51.55395365,  72.71585424, 120.2495925 ,  85.44034877,
        73.08692266,  44.11583061,  76.68506378, 108.04822467,
        85.10537837,  50.08231182, 103.61935117,  60.34995187,
        65.88682369,  63.51439586,  52.56778561,  49.80820413,
        85.08866986,  35.61075904,  47.49923708,  59.86981088,
       117.0629529 , 129.00670081,  66.94388767, 102.49600599,
        56.21824572,  49.26821516,  32.7033078 , 115.52922612,
        59.23650705,  29.31621831,  71.77241259,  63.16525647,
        71.13202541,  42.76981062,  46.83729342,  81.20567197,
        66.12754414,  71.90002679,  62.73643826,  61.03980148,
        43.32585167,  80.22948302, 101.87125865,  45.82319417,
        45.6844867 ,  57.86185022, 133.42202246,  70.55893652,
       142.18947184,  65.02264583,  53.70136559,  41.31904864,
        64.75751665,  64.59705754,  63.52335219, 132.889419  ,
        67.70928301, 101.23643707,  99.73801846,  62.84704353,
        66.2181869 ,  55.98564089,  45.71829809,  54.74544911,
        57.17785066,  63.74116863, 107.49303026,  63.83811905,
        49.39718713,  46.78780347,  85.21049434,  83.31695098,
        40.20435905,  37.28340726,  41.96876762,  51.31612366,
        53.65607307, 107.03708077,  52.19351594, 101.66525315,
        38.27402716,  76.51937304,  55.84320751, 132.55689755,
        49.87797357,  44.49640519,  71.37441272, 102.43211628,
        77.72987722,  43.63352966, 135.19594252,  51.35436153,
        49.45956504, 137.85875425,  60.9031776 ,  68.10594542,
        59.30378739, 117.53785069,  64.34908428,  62.97171009,
        58.83282866,  52.88925898,  59.8513517 ,  33.94116389,
       110.85059266, 106.4834327 ,  44.97975689,  46.40092638,
       103.66916522,  55.04218409,  83.75297955,  65.46793419,
        60.453225  ,  53.49879888,  36.38761421,  63.78064043,
        45.53386953,  62.12875839,  39.61615977,  46.24875604,
       112.13228187,  63.99822879,  55.1518553 ,  51.75127316,
        69.64059582,  36.16699311,  95.89931131,  73.1215215 ,
       118.57322632,  40.32781774,  61.87101588,  62.79405035,
        47.14224895,  50.73425107,  45.30562643,  71.28475934,
        67.79177799,  56.05237912,  45.11917956,  62.90655122,
       141.65953398,  54.71446827,  41.75936621,  66.88182135,
       107.00191389,  53.48129533,  66.16188181,  58.18420805,
        61.17221181,  70.53749817,  49.97450852,  83.52728241,
       146.35806236,  79.07485122, 135.25919492,  46.10313652,
        47.71218555,  33.9016752 ,  55.3545475 ,  50.14512705,
        61.52451416,  68.15111283,  61.69646862, 122.65594866,
        39.71788662,  45.48993844,  55.25182804,  72.70683229,
        60.9548643 ,  73.72895275,  64.5798601 ,  58.28745802,
        44.18945927,  51.52571909, 123.55526917,  58.89405324,
        67.76904694, 113.70715906,  39.9272828 ,  63.05309043,
        39.3175464 ,  48.20212591,  77.08668991,  36.21818315,
        49.56803099,  43.67453416,  82.20117893,  54.03179981,
        54.1629106 ,  44.8124953 ,  49.13243915,  55.85652142,
       112.75744312,  41.55595177,  70.26905539,  34.83710863,
        53.89955193,  80.05847111,  62.92897461,  43.92346417,
        52.20308024, 109.58739557,  56.99204735,  82.4719184 ,
        44.74275324,  48.33170238,  55.88328114,  34.65734276,
        53.08354845, 116.53000943,  54.79107397, 106.73640109,
        46.74210899,  83.52550851, 107.96530934,  43.22521533,
        34.63175015,  32.34878873,  51.24845846, 150.94119855,
        61.56139062,  62.00306973,  38.09696098,  63.88174478,
        48.17265366, 107.67086396,  61.88313957,  87.97749306,
        52.41625191, 127.40822286,  55.84614763,  53.51011395,
        52.42573632,  55.2040208 ,  39.93519683, 123.57144293,
       120.59449286,  49.49587069,  47.11608581,  68.508713  ,
       139.57237457, 120.03862254,  58.73431913,  61.36544101,
        51.76414646,  40.50646187,  73.7812705 ,  41.37271422,
        58.1563167 ,  69.23694759, 121.78396001,  58.21503645,
        59.2961728 ,  54.41963562,  44.02789992,  49.02669813,
        57.31787351,  46.13753535,  41.3861933 , 130.99886369,
        34.80182007,  48.37054158,  48.51604444,  54.56322144,
        46.74659326, 118.83958969,  60.60010212,  69.49952376,
        58.6697125 ,  52.14174212,  74.65461419, 107.79708479,
        47.56806968,  42.83764409,  56.99330226,  69.64116582,
        45.97611052,  60.28786046, 133.3567413 ,  58.97275513,
        42.1973988 ,  72.68716309,  48.30191199,  57.46260294,
       122.08128695, 129.84894086, 111.63365877,  50.53852813,
        66.65571838,  48.60913854,  80.53551761,  75.30138979,
       121.81069753,  49.2552598 ,  62.72048545,  45.69779654,
        58.94055579, 119.12803095,  60.41158439, 125.2631102 ,
        59.06557019,  47.32765365,  43.01984028,  69.53531302,
        56.06738031,  55.84241509,  52.06946579,  85.06063464,
        33.63982756, 134.10455373,  53.66554094,  36.30343531,
        52.81473716,  51.62923562,  85.62900368,  72.91727992,
        64.15317995,  50.98875696,  93.88682705,  50.51638588,
        39.14412646, 121.26499858,  47.01521624,  58.3709332 ,
        75.28084625,  43.73652326,  53.73487764,  44.34784894,
        64.48192278,  54.24342022,  40.4428632 ,  55.59245448,
        50.76251233,  52.64244918, 120.03381206,  64.56162004,
        60.2793546 ,  33.66905284,  60.70333455, 117.90037203,
        66.84283963,  80.38702247,  49.10389741,  54.17693907,
        86.19961531,  55.1821399 ,  77.45015903,  53.29935747,
        67.48623007,  60.77937461,  90.99367267,  46.20612162,
        81.94402219, 131.97088937,  64.94114096,  41.13734512,
        56.21581683, 115.05535999,  27.48529166,  62.67712552,
        60.84143581,  50.9658115 ,  62.49090135,  92.66247685,
        51.01887658, 117.52032208,  64.49754893, 119.43696501,
        40.52971981,  43.02562736,  59.53046413, 108.86126188,
       118.58078343,  93.5054485 ,  54.28632045,  73.20285166,
        61.55901161,  52.65984102, 114.58429753,  72.95100831,
        78.86282804,  78.82761578,  62.87943975,  58.68113313,
       124.19284443,  50.37693366,  40.70252705, 136.32343631,
        90.12632116,  77.51333837, 129.65748258,  39.66697457,
        54.13426143,  96.34944797,  89.42027016,  58.83812096,
        39.30763313,  71.32388669,  41.79445416,  58.0682181 ,
       128.96242718, 109.71170488,  47.3306687 ,  64.51904753,
        75.43224705,  52.72287448,  52.13003301,  36.31165549,
        75.90332066, 117.87808416,  39.3108013 ,  35.35668149,
       109.76221809,  57.92455018,  69.67987982,  45.51591884,
       120.65805019,  38.97760363,  72.98513032,  47.7685307 ,
        56.37281733,  60.71273487, 124.08036291,  48.41192532,
        64.01554213,  72.70762958, 105.426737  ,  42.1715556 ,
        34.67071376,  44.45460419, 111.67104155,  39.9523559 ,
        37.03002702,  67.65008931, 127.53522756,  59.81655236,
        44.51062961,  47.37759349, 133.12323186,  45.6235542 ,
        49.59911237,  53.10235057,  61.19388128, 105.93183092,
        70.83587394,  67.22233016,  34.08811039,  46.5888611 ,
        45.86022699,  46.00161335,  66.65020818,  36.02464103,
        53.74400572,  56.74528775,  45.30566838,  45.76255444,
        42.05678128,  48.8643528 ,  46.54468432,  63.94879214,
        49.50321715,  52.44599443,  53.86101376,  54.33482461,
       106.07697875,  68.30183202, 107.37668435,  38.26417009,
        37.15195214, 112.12131406,  60.07042248, 112.56687427,
        52.62013054,  57.723854  ,  65.41390015,  56.37491316,
        39.72718057,  66.77265279,  63.00399433,  71.29311997,
        89.42313377,  35.0350485 ,  65.363029  ,  54.64596057,
        77.25451756,  60.68615374,  62.45878044, 117.6177291 ,
        46.78227916,  42.27418312,  51.81254955,  58.98536005,
       117.31477295, 112.46894008,  61.35770174,  59.49322982,
       132.48462064,  47.62593996,  31.81126195, 132.17983922,
       113.75098307,  66.64556967,  64.36349824,  65.42095353,
        52.13311758,  52.27378674,  52.24660986,  58.28892008,
       120.74022694,  47.08503365,  51.05878867,  56.60460408,
        48.35378383,  70.54576138, 117.03387272,  51.66092857,
        49.38911992,  45.37105743, 109.9058637 ,  81.36771093,
        26.68614344,  31.76820704,  50.49988106,  59.75915579,
        43.88134439,  36.77783396,  42.31538743, 125.41658662,
        39.41179817,  53.29595673,  64.81291192, 135.20842456,
        53.8529788 ,  55.76390318,  55.97756578,  51.9357995 ,
        33.002715  ,  54.56263324, 106.11668956,  72.56756713,
        55.71442227,  57.94647531,  57.01888926,  65.53131774,
        64.308867  ,  53.60609119,  64.26183331,  68.3714677 ,
        32.22092413,  38.96109621,  54.96113417,  74.23935131])

## 🔰 Accuracy

In [22]:
ac = accuracy_score(y_test, y_pred)

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

## 🔰 r2_score

In [23]:
r2 = r2_score(y_test, y_pred)

In [24]:
r2

0.5481551574400072