# 🔷 One-Hot Encoding

### 👉 Creates separate columns for each category.

### 👉 Converts categories into numbers while keeping order.

### 👉 Each category → separate column

## 🧠 When to use One-Hot?
#### ✔ City
#### ✔ Country
#### ✔ Product type
#### ✔ Department

## 🔰 Import Library

In [1]:
import pandas as pd

## 🔰 Convert To OneHotEncoding

In [2]:
data = { "brand": ["Samsung", "Apple", "MI", "Samsung"] }

In [3]:
df = pd.DataFrame(data)

In [4]:
df

     brand
0  Samsung
1    Apple
2       MI
3  Samsung

## 🔰 Method : 1

In [5]:
encoder = pd.get_dummies(df["brand"])

In [6]:
encoder

   Apple     MI  Samsung
0  False  False     True
1   True  False    False
2  False   True    False
3  False  False     True

In [7]:
data_encoder = pd.concat([df, encoder], axis=1)

In [8]:
data_encoder

     brand  Apple     MI  Samsung
0  Samsung  False  False     True
1    Apple   True  False    False
2       MI  False   True    False
3  Samsung  False  False     True

## 🔰 Method : 2

## 🔰 Import Library

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
encoders = OneHotEncoder(sparse_output=False)

In [12]:
encoders_data = encoders.fit_transform(df[["brand"]])

In [13]:
encoders_data

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
data_encoders = pd.DataFrame(encoders_data, columns=encoders.get_feature_names_out(["brand"]))

In [15]:
data_encoders

   brand_Apple  brand_MI  brand_Samsung
0          0.0       0.0            1.0
1          1.0       0.0            0.0
2          0.0       1.0            0.0
3          0.0       0.0            1.0