# 📉 LOGISTIC REGRESSION

## 🧩 Import Library

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

## 🧩 Load the CSV File

In [2]:
df = pd.read_csv("mobile_project.csv")

In [3]:
df

      battery_power  blue  clock_speed  dual_sim  fc  four_g  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0               842     0          2.2         0   1       0  ...     7         19        0             0     1            1
1              1021     1          0.5         1   0       1  ...     3          7        1             1     0            2
2               563     1          0.5         1   2       1  ...     2          9        1             1     0            2
3               615     1          2.5         0   0       0  ...     8         11        1             0     0            2
4              1821     1          1.2         0  13       1  ...     2         15        1             1     0            1
...             ...   ...          ...       ...  ..     ...  ...   ...        ...      ...           ...   ...          ...
1995            794     1          0.5         1   0       1  ...     4         19        1             1     0            0
1996           1965     1          2.6         1   0       0  ...    10         16        1             1     1            2
1997           1911     0          0.9         1   1       1  ...     1          5        1             1     0            3
1998           1512     0          0.9         0   4       1  ...    10         19        1             1     1            0
1999            510     1          2.0         1   5       1  ...     4          2        1             1     1            3

[2000 rows x 21 columns]

In [4]:
df.head()

   battery_power  blue  clock_speed  dual_sim  fc  four_g  ...  sc_w  talk_time  three_g  touch_screen  wifi  price_range
0            842     0          2.2         0   1       0  ...     7         19        0             0     1            1
1           1021     1          0.5         1   0       1  ...     3          7        1             1     0            2
2            563     1          0.5         1   2       1  ...     2          9        1             1     0            2
3            615     1          2.5         0   0       0  ...     8         11        1             0     0            2
4           1821     1          1.2         0  13       1  ...     2         15        1             1     0            1

[5 rows x 21 columns]

## 🧩 x & y

In [5]:
y = df['price_range']

In [6]:
x = df.drop("price_range", axis=1)

## 🧩 Apply Train–Test Split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [8]:
x_train

      battery_power  blue  clock_speed  dual_sim  fc  four_g  ...  sc_h  sc_w  talk_time  three_g  touch_screen  wifi
968            1923     0          0.5         1   7       0  ...    10     9          3        1             1     1
240             633     1          2.2         0   0       1  ...    11     1         16        1             1     1
819            1236     0          0.9         1   2       1  ...    14    12         20        1             0     1
692             781     0          1.1         0   2       0  ...    13     8          5        0             0     1
420            1456     1          0.5         1   7       0  ...     6     5         20        1             0     1
...             ...   ...          ...       ...  ..     ...  ...   ...   ...        ...      ...           ...   ...
1130           1975     1          1.9         1   2       0  ...    13     5         19        0             0     1
1294            589     1          0.5         0   1       1  ...    16    10          6        1             1     1
860            1829     1          0.5         0   0       1  ...    16    11         12        1             0     1
1459           1927     0          0.9         1   3       0  ...    16    11         18        0             1     1
1126            635     1          0.6         1   1       1  ...    13    12         12        1             0     0

[1600 rows x 20 columns]

In [9]:
y_train

968     1
240     2
819     0
692     3
420     1
       ..
1130    3
1294    0
860     2
1459    3
1126    1
Name: price_range, Length: 1600, dtype: int64

## 🧩 Model

In [10]:
model = LogisticRegression()

In [11]:
model.fit(x_train, y_train)

C:\Users\baps\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

## 🧩 Prediction & Evaluation

In [12]:
y_pred = model.predict(x_test)

In [13]:
y_pred

array([0, 2, 0, 3, 1, 2, 3, 0, 3, 3, 0, 1, 2, 3, 3, 2, 2, 2, 1, 0, 0, 1,
       0, 2, 1, 1, 3, 3, 3, 0, 1, 0, 3, 0, 2, 3, 2, 1, 3, 0, 1, 2, 3, 0,
       3, 3, 3, 1, 3, 1, 3, 2, 0, 0, 2, 0, 2, 2, 0, 0, 1, 3, 3, 2, 2, 0,
       3, 3, 1, 1, 2, 2, 0, 1, 2, 0, 0, 3, 1, 2, 3, 2, 1, 0, 1, 3, 3, 3,
       3, 0, 3, 3, 3, 0, 3, 2, 2, 3, 2, 1, 0, 1, 0, 0, 0, 3, 3, 0, 0, 1,
       0, 0, 3, 3, 2, 1, 3, 3, 0, 2, 1, 3, 2, 1, 3, 3, 0, 3, 0, 2, 3, 0,
       2, 2, 0, 2, 1, 1, 0, 2, 3, 1, 3, 3, 0, 0, 1, 2, 1, 2, 3, 1, 2, 0,
       2, 3, 0, 1, 0, 1, 3, 3, 2, 2, 1, 0, 0, 2, 1, 3, 3, 1, 0, 0, 3, 1,
       1, 2, 0, 1, 0, 0, 0, 1, 3, 2, 0, 2, 0, 0, 0, 0, 1, 3, 3, 1, 0, 1,
       1, 1, 1, 2, 1, 2, 3, 3, 1, 3, 0, 1, 1, 1, 1, 1, 3, 2, 1, 3, 1, 1,
       3, 2, 3, 0, 0, 3, 0, 2, 0, 0, 1, 0, 2, 3, 2, 1, 0, 2, 3, 1, 3, 3,
       2, 3, 0, 3, 2, 2, 2, 3, 3, 1, 1, 3, 2, 1, 2, 3, 3, 3, 3, 0, 2, 2,
       2, 2, 3, 0, 3, 3, 2, 2, 2, 0, 1, 3, 0, 2, 3, 1, 3, 1, 1, 2, 0, 3,
       0, 0, 3, 0, 1, 2, 3, 2, 2, 0, 1, 0, 0, 3, 3, 0, 1, 1, 2, 0, 3, 3,
       3, 3, 1, 3, 2, 0, 3, 2, 3, 2, 0, 0, 1, 3, 2, 3, 1, 1, 2, 0, 3, 3,
       2, 0, 2, 2, 1, 2, 3, 1, 0, 3, 1, 2, 2, 1, 1, 1, 2, 2, 3, 3, 1, 1,
       1, 2, 2, 0, 3, 0, 0, 2, 0, 0, 1, 2, 2, 3, 0, 1, 2, 3, 3, 3, 2, 3,
       1, 2, 0, 2, 1, 3, 3, 0, 1, 3, 2, 3, 2, 3, 1, 0, 3, 2, 0, 0, 3, 3,
       1, 2, 3, 2])

## 🧩 accuracy_score Apply

In [14]:
acc_score = accuracy_score(y_pred, y_test)

In [15]:
acc_score

0.6325